### ISSUE TITLE
suggested stylistic/cosmetic improvements

### ISSUE THREAD

**Issue by klaeufer** [sshilpika/literalinclude-scala#4]
- Consider eliminating definitions for vals that you return on the next line: l34, l43, l80
- Consider eliminating type annotations for local vals: l41
- You probably don't need the empty string argument in l44
- Eliminate unused imports
- I think you can use the DSL to build the URLs instead of doing this at the String level?

**Comment by sshilpika** [comment]
Fixed the first four.
For point 5, Will it make a difference? Also, just to clarify you are talking about DSL at the request level invocation?

**Comment by klaeufer** [comment]
Great progress!

Regarding point 5, I reviewed the examples again and don't think we need to worry about it.

I did notice a few more very minor cosmetic issues (missing spaces after if or before else, blank lines, indentation/placement of braces), so perhaps you can take one more quick look and close the issue.

**Comment by sshilpika** [comment]
Used IDE to add formatting. I can close this issue if your are ok with the formatting

**Comment by sshilpika** [comment]
I have used some really cool case class validations! Got rid of the if-else checks in the runRoute wrapper.
