### ISSUE TITLE
should use "global" ActorSystem defined in Boot throughout service

### ISSUE THREAD

**Issue by klaeufer** [sshilpika/literalinclude-scala#5]
See also http://stackoverflow.com/a/10397403/4778618.

You should definitely not create them on a per-request basis (l32, l78)!

I think the solution is here: http://stackoverflow.com/questions/25472019

We can pair on this...

**Comment by sshilpika** [comment]
I have a question here, if i create one actor at Boot.scala then won't this be a performance bottle neck, actors handle one request at a time as per what I understand.

**Comment by klaeufer** [comment]
1) No performance bottleneck... The spray architecture takes care of this: http://spray.io/documentation/1.2.2/spray-can/http-server/#basic-architecture

2) I was talking about the ActorSystem. Very expensive to create. We should use only the one defined in Boot, so we need to figure out how to access it within HttpService.

**Comment by sshilpika** [comment]
Made some changes here.

**Comment by sshilpika** [comment]
I used HttpServiceActor instead of HttpService, this already connects the context in the trait! If you have a better suggestions let me know.

**Comment by klaeufer** [comment]
Great work!
